### ISSUE TITLE
Panic in `ico::IconDirEntry::decode`

### ISSUE THREAD

**Issue by rfuzz** [mdsteele/rust-ico#7]
Hey there,

I've uncovered a critical issue while fuzzing our crate. There's a panic occurring in the `ico::IconDirEntry::decode` function when it encounters ICO images with absurdly large biWidth and biHeight values in the bmiHeader.

Specifically, the panic happens when the product of these dimensions overflows usize.

```rust
use std::fs::File;
use ico::{IconDir, IconDirEntry};

fn main() {
    if let Ok(file) = File::open("crash.ico") {
        if let Ok(icon_dir) = IconDir::read(file) {
            for entry in icon_dir.entries() {
                if let Err(e) = entry.decode() {
                    eprintln!("Decoding error: {}", e);
                }
            }
        }
    }
}
```

crash.ico [download](https://github.com/rfuzz/crash-inputs/raw/refs/heads/main/rust-ico/crash.ico)

Running this with our problematic `crash.ico` file results in:

```shell
thread 'main' panicked at /home/ubuntu/rust-ico/src/image.rs:295:26:
attempt to multiply with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Version: `commit d1ae9e4582cd5d258046b7788ce7aa0fcbaa0a20`

**Comment by mdsteele** [comment]
My guess is that the problematic lines are these ones in `IconImage::read_bmp`:

```rust
        let num_pixels = (width * height) as usize;
        let mut rgba = vec![u8::MAX; num_pixels * 4];
```

`width` and `height` each have type `u32` at this point.  Probably these multiplies should be replaced with `usize::checked_mul`, and `read_bmp` should return an `Error` on overflow.  (Also, `width` and `height` should be getting cast to `usize` _before_ the multiply, not after.)

Would you be interested in making a PR?
